name: snaplink_app
description: "Snaplink Social Application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.26.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.0.16
  firebase_auth: ^4.17.7


  random_string: ^2.3.1
  fluttertoast: ^8.2.8
  image_picker: ^0.8.5+3
  permission_handler: ^10.2.0

  google_sign_in: ^6.1.5
  cupertino_icons: ^1.0.8

  go_router: ^14.3.0
  easy_localization: ^3.0.7
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  camera: ^0.10.5+9
  gap: ^3.0.1
  external_path: ^2.0.1
  photo_manager: ^3.6.0

  video_player: ^2.4.5
  uuid: ^3.0.6
  video_compress: ^3.1.0
  cached_network_image: ^3.2.0
  timeago: ^3.2.2

  google_fonts: ^6.2.1
  animation_wrappers: ^3.0.0

  animated_splash_screen: ^1.3.0
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/translations/en.json
    - assets/translations/vi.json
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/
    - assets/images/
    - assets/thumbnails/
    - assets/user/
    - assets/videos/
    - assets/icons/
    - assets/thumbnails/dance/
    - assets/thumbnails/lol/
    - assets/thumbnails/food/
